### ISSUE TITLE
 CSS Focus bug

### ISSUE THREAD

**Issue by karanb1** [fluid-project/floeproject.org#102]
Even if we move to another option on the resources page the option we clicked previously remain on focus.
<img width="1280" alt="Screenshot 2020-02-23 at 7 40 40 AM" src="https://user-images.githubusercontent.com/53102310/75102377-732cc200-5610-11ea-8e67-288ee7970b09.png">

**Comment by jhung** [comment]
@karanb1 can you describe the steps to reproduce this issue?

In the future, please follow the templates for _Enhancement_ and _Bug_ reports. What you are reporting sounds like a _Bug_ and should follow the template when reporting a Github issue.

**Comment by karanb1** [comment]
I apologise for not following the template. 
To reproduce: click on a button and then move to another option the previously clicked button remain on focus.

The hover effect works but the focus on the previously clicked button is not suitable for keyboard users and there is a sense of confusion that on which option they are currently at.

**Comment by jobara** [comment]
@karanb1 could you please provided detailed step-by-step instructions for reproducing this issue and include which browser and platform you experienced it on? I'm not seeing the issue, but I may not be understanding the problem or not using the correct steps to reproduce it.

**Comment by karanb1** [comment]
<img width="1280" alt="Screenshot 2020-02-23 at 7 40 40 AM" src="https://user-images.githubusercontent.com/53102310/75407083-214daa00-5938-11ea-8458-09c2fed2c837.png">
I am using google chrome for MacOS

**Comment by jobara** [comment]
@karanb1 thanks for the information. It's still not clear to me if this is an issue and that is because there is some ambiguity in your instructions. When you say "moved to another option" you don't mention what method you used to move to another option. If you use the keyboard to focus "Multimodal Presentation, Content Adaptation and Personal Preferences" and then used the mouse to hover "Inclusive Design Practice", I don't think there is an issue. 

Also, please don't add your steps to the screen shot. It's hard to read because the image is rendered smaller in the conversation thread and for those who have a visual impairment, they may not be able to perceive it at all. The information should be described in text, and an image used as an alternate presentation to provide visual clarity.

**Comment by karanb1** [comment]
I apologise for adding steps in the screenshot. It will not happen again.

**Comment by greatislander** [comment]
Thanks for this report, however this behaviour is expected and we won't be changing it.
