### ISSUE TITLE
Incorporate suggested content changes

### ISSUE THREAD

**Issue by greatislander** [fluid-project/floeproject.org#193]
## Is your feature request related to a problem?

Jutta suggested some content changes: https://lists.idrc.ocad.ca/pipermail/fluid-work/2014-April/009363.html

## Describe the solution you'd like

These should be incorporated if still relevant.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

Replaces [FLOE-185](https://issues.fluidproject.org/browse/FLOE-185).

**Comment by patelaryan7751** [comment]
can i work on this issue?

**Comment by colinbdclark** [comment]
Hi @patelaryan7751, I don't think this is a particularly good first issue for someone who is new to our community, since it involves a lot of background knowledge of the project and our goals. Also, in case you're interested in Google Summer of Code, please note that we will not be participating in the program this year.

**Comment by patelaryan7751** [comment]
@colinbdclark okay !

**Comment by jhung** [comment]
Addressed in #232
